import { genCreateElement } from './core'

export const br = genCreateElement('br')
export const p = genCreateElement('p')
export const input = genCreateElement('input')
export const label = genCreateElement('label')
export const span = genCreateElement('span')
export const button = genCreateElement('button')
export const h1 = genCreateElement('h1')
export const h2 = genCreateElement('h2')
export const h3 = genCreateElement('h3')
export const h4 = genCreateElement('h4')
export const h5 = genCreateElement('h5')
export const h6 = genCreateElement('h6')
export const b = genCreateElement('b')
export const i = genCreateElement('i')
export const img = genCreateElement('img')
export const audio = genCreateElement('audio')
export const video = genCreateElement('video')
