import { genCreateHTMLElement } from './core'

export const br = genCreateHTMLElement('br')
export const p = genCreateHTMLElement('p')
export const a = genCreateHTMLElement('a')
export const div = genCreateHTMLElement('div')
export const form = genCreateHTMLElement('form')
export const input = genCreateHTMLElement('input')
export const label = genCreateHTMLElement('label')
export const span = genCreateHTMLElement('span')
export const button = genCreateHTMLElement('button')
export const h1 = genCreateHTMLElement('h1')
export const h2 = genCreateHTMLElement('h2')
export const h3 = genCreateHTMLElement('h3')
export const h4 = genCreateHTMLElement('h4')
export const h5 = genCreateHTMLElement('h5')
export const h6 = genCreateHTMLElement('h6')
export const b = genCreateHTMLElement('b')
export const i = genCreateHTMLElement('i')
export const img = genCreateHTMLElement('img')
export const audio = genCreateHTMLElement('audio')
export const video = genCreateHTMLElement('video')
export const ol = genCreateHTMLElement('ol')
export const ul = genCreateHTMLElement('ul')
export const li = genCreateHTMLElement('li')
export const code = genCreateHTMLElement('code')
